version: "3.8"

services:
  backend:
    build: ./backend
    container_name: expense-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # <-- Change this to depend on the service's health
    networks:
      - expense-net
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    container_name: expense-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - expense-net

  db:
    image: mysql:8.0
    container_name: expense-db
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: expensesharing
      MYSQL_USER: expense_user
      MYSQL_PASSWORD: password123
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - expense-net
    healthcheck: # <-- Add this healthcheck for the database
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uexpense_user", "-ppassword123"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  expense-net:
    driver: bridge